version: '3.1'
services:
  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '46000:80'

  php-fpm:
    build: .
    working_dir: /application
    volumes:
      - '.:/application'
    command: >
      sh -c "composer install && php-fpm"
