services:
  php-fpm:
    build: .
    volumes:
      - .env:/app/.env
      - ./public:/app/public
    environment:
      KODY_HOSTNAME: "grpc-staging.kodypay.com"
      KODY_STORE_ID: "c4cebf51-b006-4bb9-acd5-bb4bcdbd6e09"
      KODY_API_KEY: "0aY8Gqnx95WpmGnl6w8bxYO99As1vycBsb6soE_CQwd2"
      PAYMENT_EXPIRING_SECONDS: 900

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
