name: PHP7 Build and Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  prepare-grpc-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Cache gRPC PHP plugin
        uses: actions/cache@v4
        id: cache-grpc-php-plugin
        with:
          path: |
            ./grpc/cmake/build
          key: ${{ runner.os }}-grpc-php-plugin-v1_64_2

      - name: Build gRPC PHP plugin
        if: steps.cache-grpc-php-plugin.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y build-essential autoconf libtool pkg-config
          git clone --recurse-submodules -b v1.64.2  https://github.com/grpc/grpc
          cd grpc
          mkdir -p cmake/build
          cd cmake/build
          cmake ../..
          make grpc_php_plugin  

  build-package:
    needs:
      - prepare-grpc-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout proto repository
        run: |
          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, json, grpc, protobuf

      - name: Install Specific Protoc Version
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip
          unzip protoc-27.1-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/* /usr/local/bin/
          sudo mv protoc/include/* /usr/local/include/

      - name: Check Protoc Version
        run: |
          protoc --version

      - name: Cache gRPC PHP plugin
        uses: actions/cache@v4
        id: cache-grpc-php-plugin
        with:
          path: |
            ./grpc/cmake/build
          key: ${{ runner.os }}-grpc-php-plugin-v1_64_2

      - name: Install gRPC PHP plugin
        run: |
          sudo cp ./grpc/cmake/build/grpc_php_plugin /usr/local/bin/

      - name: Compile Protobuf file
        run: |
          mkdir -p php7
          protoc --proto_path=proto-repo/src/main/proto --php_out=./php7 --grpc_out=./php7 --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin proto-repo/src/main/proto/com/kodypay/grpc/pay/v1/pay.proto

      - name: Require gRPC PHP Extension in Composer
        run: composer require ext-grpc --no-update

      - name: Package the compiled files
        run: |
          zip -r kody-php7-grpc-package.zip php7

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kody-php7-grpc-package
          path: kody-php7-grpc-package.zip

  tagging:
    runs-on: ubuntu-latest
    outputs:
      tags: $
    steps:
      - name: Create and push tag
        id: tags
        run: |
          TAG=$(date +'%Y%m%d_%H%M')
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo 'tags=[$TAG,"latest"]' >> "$GITHUB_OUTPUT"
          else
            TAG=$(date +'%Y%m%d_%H%M')-dev
            echo 'tags=[$TAG]' >> "$GITHUB_OUTPUT"          
          fi
  tagging-echo:
    needs:
      - tagging
    runs-on: ubuntu-latest
    steps:
      - name: Show tag
        run: |
          echo "Tags: ${{ fromJSON(needs.tagging.outputs.tags) }}"

  release:
    needs:
      - build-package
      - tagging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.tagging.outputs.tags) }}
    steps:
      - name: Set up
        env:
          tag: $
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "$tag" > tag
          echo "Releasing TAG: $tag"

      - name: Push tag
        run: |
          git tag ${{ matrix.tag }}
          git push origin ${{ matrix.tag }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          body: |
            Changes in this release:
            ${{ github.event.release.body }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}

      - name: Retrieve Artifact
        uses: actions/download-artifact@latest
        with:
          name: kody-php7-grpc-package

      - name: Upload Release Asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: kody-php7-grpc-package.zip
          asset_name: kody-php7-grpc-package.zip
          asset_content_type: application/zip
